# Generated by Django 4.2.13 on 2024-12-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_login', 'Can view login page')]},
        ),
    ]
